Update readme
andrey-zherikov/argparse pull request #121
Opened 2023-11-18 17:27 UTC by SirNickolas

A follow-up of #109.

2023-11-20 03:41 UTC, andrey-zherikov requested changes
Thanks for suggested improvements. They look good!

Could you please return spaces back that were around dashes (that you replaced with Unicode characters)?

I also added few other comments.

2023-11-20 03:41 UTC, andrey-zherikov commented on examples/getting_started/basic/app.d
> +        // --boolean
Why is `argument` removed here?

2023-11-20 03:41 UTC, andrey-zherikov commented on examples/getting_started/basic/app.d
> +        // --callback
ditto

2023-11-20 03:41 UTC, andrey-zherikov commented on README.md
> +        // --boolean
Why is `argument` removed?

2023-11-20 03:41 UTC, andrey-zherikov commented on README.md
> +        // --callback
ditto

2023-11-20 03:41 UTC, andrey-zherikov commented on README.md
> +Using colors in your command’s output does not just look good: **contrasting** important elements like argument names,
I'm not sure that comma is needed here

2023-11-20 03:41 UTC, andrey-zherikov commented on README.md
> +Any arbitrary type can be used to receive command-line-argument values. `argparse` supports this use case—you just need
Should it be `command-line argument`?

2023-11-20 03:41 UTC, andrey-zherikov commented on README.md
> +`Config.arraySep`—when set to `char.init`, values to array and associative-array receivers are treated as an individual
Just `associative array`

2023-11-20 07:40 UTC, SirNickolas commented on examples/getting_started/basic/app.d
> +        // --boolean
Because a boolean (i.e., flag) parameter does not accept a value as a separate argument. `./prog --boolean true` is incorrect; you use either `./prog --boolean=true` or plain `./prog --boolean`. So I updated the docs to reflect that fact.

What do you think about `// --boolean[=argument]`? Is it clear enough?

2023-11-20 07:40 UTC, SirNickolas commented on README.md
> +Using colors in your command’s output does not just look good: **contrasting** important elements like argument names,
My bad. It appeared by accident here. Thanks!

2023-11-20 07:40 UTC, SirNickolas commented on README.md
> +Any arbitrary type can be used to receive command-line-argument values. `argparse` supports this use case—you just need
In this sentence, *values* is the object that is *received*; *command(?)line(?)argument* is a compound adjective that describes it. But *command-line* is itself a compound adjective, too.

I did some googling and found out there are two grammatically correct choices here: *command-line-argument* (two hyphens) or *command line–argument* (a space and an en dash—not an em dash, which is used in the rest of the document!). Which one do you prefer?

https://www.dailywritingtips.com/en-dashes-clarify-compound-phrasal-adjectives/
https://www.grammarbook.com/blog/adjectives-adverbs/the-elusive-en-dash/

2023-11-20 07:40 UTC, SirNickolas commented on README.md
> +`Config.arraySep`—when set to `char.init`, values to array and associative-array receivers are treated as an individual
I disagree. *Receivers* is the object in this sentence *(…values to receivers are treated as an individual value)*. So *associative-array* is again a compound adjective, which should be hyphenated.

2023-11-20 07:40 UTC, SirNickolas commented
> Could you please return spaces back that were around dashes (that you replaced with Unicode characters)?

Turns out it’s a British/American difference. BrE style guides recommend using **en** dashes surrounded with spaces while AmE suggest unspaced **em** dashes. I guess the former looks more appealing to you, doesn’t it?

https://practicaltypography.com/hyphens-and-dashes.html
https://english.stackexchange.com/questions/497006/in-britain-which-is-more-common-the-em-dash-or-the-en-dash

I’ll perhaps fix everything in one commit.

2023-11-20 08:17 UTC, SirNickolas commented on examples/getting_started/basic/app.d
> +        // --callback
Because this callback does not take arguments. Even `--callback=argument` is invalid.

2023-11-20 08:50 UTC, SirNickolas commented on README.md
> +`Config.arraySep`—when set to `char.init`, values to array and associative-array receivers are treated as an individual
That is,
1. an associative-array receiver = a receiver that is an associative array;
2. an associative array receiver = an associative receiver that is an array.

2023-11-20 20:08 UTC, andrey-zherikov commented on examples/getting_started/basic/app.d
> +        // --boolean
Word "argument" here doesn't mean a argument value. This means "argument that appears as `--boolean` in command line". The same as for other arguments: e.g. "argument that appears as `--number ` in command line"

2023-11-20 20:08 UTC, andrey-zherikov commented on examples/getting_started/basic/app.d
> +        // --callback
The same: word "argument" doesn't mean a value here

2023-11-20 20:12 UTC, andrey-zherikov commented on README.md
> +`Config.arraySep`—when set to `char.init`, values to array and associative-array receivers are treated as an individual
Let's leave it with a dash

2023-11-20 20:14 UTC, andrey-zherikov commented
> I guess the former looks more appealing to you, doesn’t it?

Yes, IMO it's a bit more readable with spaces around.

2023-11-21 03:54 UTC, SirNickolas commented on examples/getting_started/basic/app.d
> +        // --boolean
I’ve never thought it could be read like this.

2023-11-22 04:12 UTC, andrey-zherikov approved these changes

2023-11-22 04:12 UTC, andrey-zherikov commented on README.md
> +`Result parseArgs(ref COMMAND receiver, string[] args)`
Nice catch!

2023-11-22 04:12 UTC, merged